---
title: "exp2fix"
author: "Will Clapp"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(psych)
library(lme4)
```


Load data
```{r}
df.data <- read.csv("/Users/willclapp/Desktop/QP1/QP1_Experiments/Exp_2/Analysis/raw/Exp_2_first_times.csv")
```


Get rid of the messed up data

All data is tainted from prd, prg, crd, and crg, so filter these out 45080 
```{r}
df.healthy <- df.data %>% 
  filter(!(group == "P_group" & yes_side == "right")) %>% 
  filter(!(group == "control" & yes_side == "right"))

bads = c("22d42c08-b4ca-4413-b2c3-e059a9a83724", "23907585-5b4a-4a61-9819-3f16a733fdaf", "04a20508-5fa6-49e5-801f-b4abe4d5162f", "780a4aa5-820f-40d9-a8e6-ed7806dc1598")

df.healthy <- df.healthy %>% 
  filter(!(participant_id %in% bads))

write.csv(df.healthy, "/Users/willclapp/Desktop/QP1/QP1_Experiments/Exp_2/Analysis/Exp_2_raw_healthy.csv")

df.2 <- read.csv("/Users/willclapp/Desktop/QP1/QP1_Experiments/Exp_2/Analysis/raw/Exp_2_second_times.csv")

df.both <- rbind(df.healthy, df.2)

write.csv(df.both, "/Users/willclapp/Desktop/QP1/QP1_Experiments/Exp_2/Analysis/Exp_2_raw.csv")

```


Data is tainted from brd redux
times are 25.25, 27.8, and 20.37
previous n = 45080

22d42c08-b4ca-4413-b2c3-e059a9a83724
23907585-5b4a-4a61-9819-3f16a733fdaf
04a20508-5fa6-49e5-801f-b4abe4d5162f
780a4aa5-820f-40d9-a8e6-ed7806dc1598

```{r}
df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "right" & test_order == "BDG" & time_in_minutes > 25.2 & time_in_minutes < 25.3) 


df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "right" & test_order == "BDG" & time_in_minutes > 27.7 & time_in_minutes < 27.9)

df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "right" & test_order == "BDG" & time_in_minutes > 20.2 & time_in_minutes < 20.45)
```


Data is tainted from bLd redux
times are 23.2, 24.83, and 25.93 and 21.05
previous n = 44160
```{r}
df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "left" & test_order == "BDG" & time_in_minutes > 23.15 & time_in_minutes < 23.25)

df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "left" & test_order == "BDG" & time_in_minutes > 24.78 & time_in_minutes < 24.88)

df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "left" & test_order == "BDG" & time_in_minutes > 25.8 & time_in_minutes < 25.98)

df.bad <- df.healthy %>% 
  filter(group == "B_group" & yes_side == "left" & test_order == "BDG" & time_in_minutes > 20.25 & time_in_minutes < 20.45)

```

PLG 29.4 27.02 21.98 31.17
```{r}
df.bad <- df.healthy %>% 
  filter(group == "P_group" & yes_side == "left" & test_order == "BGD" & time_in_minutes > 29.3 & time_in_minutes < 29.5)

df.bad <- df.healthy %>% 
  filter(group == "P_group" & yes_side == "left" & test_order == "BGD" & time_in_minutes > 27 & time_in_minutes < 27.1)

df.bad <- df.healthy %>% 
  filter(group == "P_group" & yes_side == "left" & test_order == "BGD" & time_in_minutes > 21.95 & time_in_minutes < 22)

df.bad <- df.healthy %>% 
  filter(group == "P_group" & yes_side == "left" & test_order == "BGD" & time_in_minutes > 31.12 & time_in_minutes < 31.22)

```



