---
title: "Pilot Analysis"
author: "Will Clapp"
date: "8/25/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(psych)
```


```{r}
df.b_left_g_first <- read.csv("/Users/willclapp/Desktop/QP1/QP1_Experiments/Exp_1/data/pilot/run-1-results.csv")
df.p_left_g_first <- read.csv("/Users/willclapp/Desktop/QP1/QP1_Experiments/Exp_1/data/pilot/run-2-results.csv")

df.data <- rbind(df.b_left_g_first, df.p_left_g_first)
```


Add column for accuracy on exposure
```{r}
df.data <- df.data %>% 
  mutate("accurate" = ifelse(((phase=="exposure") & (((response=="yes") & (correct=="yes")) | ((response=="no") & (correct=="no")))), 1, 0))

df.data <- df.data %>% 
  mutate("accurate" = ifelse((phase=="exposure"), accurate, NA))

```

```{r}
df.data <- df.data %>% 
  mutate(response_01 = ifelse(response=="yes", 1, 0))

```

```{r}
df.accuracy = df.data %>% 
  filter(phase == "exposure") %>% 
  group_by(participant_id, time_in_minutes) %>% 
  summarise(accuracy = mean(accurate))

df.data = left_join(df.data, df.accuracy, by="participant_id")

```



```{r}
df.guessers <- df.data %>% 
  filter(accuracy < 0.85)

df.listeners <- df.data %>% 
  filter(accuracy > 0.85)
```



```{r}
df.listeners %>%
  filter(type == "crit_amb") %>% 
  ggplot(aes(x = accurate)) +
  geom_bar() +
  facet_wrap(~audio)

```


```{r}
df.sep_steps = df.listeners %>% 
  filter(phase == "test") %>% 
  group_by(group, step, voiced_sel) %>% 
  summarise(mean_res = mean(response_01))


```


```{r}
df.sep_steps %>% 
  filter(voiced_sel == "B") %>% 
  ggplot(data=.,
         mapping = aes(x = step,
                       y = mean_res)) +
  geom_point(aes(color=group)) +
  geom_smooth(aes(color=group)) +
  labs(title = "B/P")

df.sep_steps %>% 
  filter(voiced_sel == "D") %>% 
  ggplot(data=.,
         mapping = aes(x = step,
                       y = mean_res)) +
  geom_point(aes(color=group)) +
  geom_smooth(aes(color=group)) +
  labs(title = "D/T")

df.sep_steps %>% 
  filter(voiced_sel == "G") %>% 
  ggplot(data=.,
         mapping = aes(x = step,
                       y = mean_res)) +
  geom_point(aes(color=group)) +
  geom_smooth(aes(color=group)) +
  labs(title = "G/K")


```



```{r}
df.labial <- df.listeners %>% 
  filter(voiced_sel=="B")
df.coronal <- df.listeners %>% 
  filter(voiced_sel=="D")
df.dorsal <- df.listeners %>% 
  filter(voiced_sel=="G")

glm.labial = glm(response_01 ~ 1 + group * step, 
                     data = df.listeners,
                     family="binomial")
glm.coronal = glm(response_01 ~ 1 + group * step, 
                     data = df.listeners,
                     family="binomial")
glm.dorsal = glm(response_01 ~ 1 + group * step, 
                     data = df.listeners,
                     family="binomial")

summary(glm.labial)
summary(glm.coronal)
summary(glm.dorsal)

```
